# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField()),
                ('last_active', models.DateTimeField()),
                ('firebase_token', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('title', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('icon', models.TextField(blank=True)),
                ('color', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('title', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('icon', models.TextField(blank=True)),
                ('color', models.TextField(blank=True)),
                ('webhook', models.CharField(blank=True, max_length=30)),
                ('raw_data', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
