# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-22 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='webhook',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
