# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('FI', 'Firebase'), ('WP', 'Web Push')], default='FB', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='web_push_auth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='web_push_endpoint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='web_push_p256dh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='firebase_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
