# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20180722_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
